# The whole suite will run tests on backend and frontend and analyze code quality
name: Login_CRUD_CI_Pipeline

# Main protected by pull request
on:
  push:
    branches: [ "devBranch" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Unittests on javascript backend in three different Node environments
  JEST_unittests:
    
    name: JEST unittests
    # OS not relevant in this test, use fastest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      # Coverage added
    - run: npm test -- --coverage

  # Frontend tests with Chrome and Edge
  Selenium_run:
    needs: [JEST_unittests]
  
    name: Selenium run

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pytest
        pip install -U Selenium
        pip install pytest-html
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Selenium test with pytest as testrunner
      run: |
        pytest -rA --verbose tests/test_UI_Selenium_2.py
  
  Code_quality_check:
    needs: [JEST_unittests]
  
    name: Code quality check

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
  Deploy:
    needs: [Selenium_run]
    
    name: Deploy Login_CRUD
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup container
      run: echo "Here goes code for creating image"



